estructura:
  title: "Estructura"
  description:
    - "Nombre abreviado"
    - "Nombre Completo"
    - "Web"
    - "Total de afiliados"
  columns:
    - nombre_abreviado
    - nombre_completo
    - web
    - afiliados
  definition:
    string:
      - nombre_abreviado
      - nombre_completo
      - web
    integer:
      - afiliados

metas:
  title: "Metas Asistenciales"
  description:
    - "Porcentaje de niños de un año correctamente controlados"
    - "Porcentaje de embarazadas correctamente controladas"
    - "Existencia de Espacio Adolescente en la institución"
    - "Comunicación en soporte electrónico (página web)"
  columns:
    - meta_ninos_controlados
    - meta_embarazadas
    - espacio_adolescente
    - comunicacion
  definition:
    decimal:
      - meta_ninos_controlados
      - meta_embarazadas
    boolean:
      - espacio_adolescente
    text:
      - comunicacion

precios:
  title: "Precios"
  description:
    - "Ticket de medicamentos - general. FONASA"
    - "Ticket de medicamentos - general. NO FONASA"
    - "Ticket de medicamentos topeados- antihipertensivos (valsartán, amlodipina, hidroclorotiazida, enalapril). FONASA"
    - "Ticket de medicamentos topeados- antihipertensivos (valsartán, amlodipina, hidroclorotiazida, enalapril). NO FONASA"
    - "Consulta no urgente consultorio - medicina general. FONASA"
    - "Consulta no urgente consultorio - medicina general. NO FONASA"
    - "Consulta no urgente consultorio - pediatria. FONASA"
    - "Consulta no urgente consultorio - pediatria. NO FONASA"
    - "Consulta no urgente consultorio - gineco-obstetricia (control de embarazo). FONASA"
    - "Consulta no urgente consultorio - gineco-obstetricia (control de embarazo). NO FONASA"
    - "Consulta no urgente consultorio - ginecologia. FONASA"
    - "Consulta no urgente consultorio - ginecologia. NO FONASA"
    - "Consulta no urgente consultorio - otras especialidades. FONASA"
    - "Consulta no urgente consultorio - otras especialidades. NO FONASA"
    - "Consulta urgencia centralizada. FONASA"
    - "Consulta urgencia centralizada. NO FONASA"
    - "Consulta no urgencia domicilio. FONASA"
    - "Consulta no urgencia domicilio. NO FONASA"
    - "Consulta urgencia domicilio. FONASA"
    - "Consulta urgencia domicilio. NO FONASA"
    - "Consulta odontologica. FONASA"
    - "Consulta odontologica. NO FONASA"
    - "Consulta medico de referencia. FONASA"
    - "Consulta medico de referencia. NO FONASA"
    - "Endoscopía digestiva. Endoscopia esofagogastroduodenal. FONASA"
    - "Endoscopía digestiva. Endoscopia esofagogastroduodenal. NO FONASA"
    - "Ecografía simple. FONASA"
    - "Ecografía simple. NO FONASA"
    - "Ecodoppler miembros (inferiores / superiores) arterial / venoso. FONASA"
    - "Ecodoppler miembros (inferiores / superiores) arterial / venoso. NO FONASA"
    - "Rx abdomen / aparato urinario simple. FONASA"
    - "Rx abdomen / aparato urinario simple. NO FONASA"
    - "Rx torax. FONASA"
    - "Rx torax. NO FONASA"
    - "Rx colorectal. (c/contraste) FONASA"
    - "Rx colorectal. (c/contraste) NO FONASA"
    - "Resonancia nuclear magnética, una región. FONASA"
    - "Resonancia nuclear magnética, una región. NO FONASA"
    - "Tomografía axial computarizada, una región. FONASA"
    - "Tomografía axial computarizada, una región. NO FONASA"
    - "Laboratorio, rutina básica. FONASA"
    - "Laboratorio, rutina básica. NO FONASA"
  columns:
    - ticket_de_medicamentos_general_fonasa
    - ticket_de_medicamentos_general_no_fonasa
    - ticket_de_medicamentos_topeados_fonasa
    - ticket_de_medicamentos_topeados_no_fonasa
    - consulta_medicina_general_fonasa
    - consulta_medicina_general_no_fonasa
    - consulta_pediatria_fonasa
    - consulta_pediatria_no_fonasa
    - consulta_control_de_embarazo_fonasa
    - consulta_control_de_embarazo_no_fonasa
    - consulta_ginecologia_fonasa
    - consulta_ginecologia_no_fonasa
    - consulta_otras_especialidades_fonasa
    - consulta_otras_especialidades_no_fonasa
    - consulta_urgencia_centralizada_fonasa
    - consulta_urgencia_centralizada_no_fonasa
    - consulta_no_urgencia_domicilio_fonasa
    - consulta_no_urgencia_domicilio_no_fonasa
    - consulta_urgencia_domicilio_fonasa
    - consulta_urgencia_domicilio_no_fonasa
    - consulta_odontologica_fonasa
    - consulta_odontologica_no_fonasa
    - consulta_medico_de_referencia_fonasa
    - consulta_medico_de_referencia_no_fonasa
    - endoscopia_digestiva_endoscopia_fonasa
    - endoscopia_digestiva_endoscopia_no_fonasa
    - ecografia_simple_fonasa
    - ecografia_simple_no_fonasa
    - ecodoppler_fonasa
    - ecodoppler_no_fonasa
    - rx_simple_fonasa
    - rx_simple_no_fonasa
    - rx_torax_fonasa
    - rx_torax_no_fonasa
    - rx_colorectal_fonasa
    - rx_colorectal_no_fonasa
    - resonancia_fonasa
    - resonancia_no_fonasa
    - tomografia_fonasa
    - tomografia_no_fonasa
    - laboratorio_rutina_basica_fonasa
    - laboratorio_rutina_basica_no_fonasa
  definition:
    decimal:
      - ticket_de_medicamentos_general_fonasa
      - ticket_de_medicamentos_general_no_fonasa
      - ticket_de_medicamentos_topeados_fonasa
      - ticket_de_medicamentos_topeados_no_fonasa
      - consulta_medicina_general_fonasa
      - consulta_medicina_general_no_fonasa
      - consulta_pediatria_fonasa
      - consulta_pediatria_no_fonasa
      - consulta_control_de_embarazo_fonasa
      - consulta_control_de_embarazo_no_fonasa
      - consulta_ginecologia_fonasa
      - consulta_ginecologia_no_fonasa
      - consulta_otras_especialidades_fonasa
      - consulta_otras_especialidades_no_fonasa
      - consulta_urgencia_centralizada_fonasa
      - consulta_urgencia_centralizada_no_fonasa
      - consulta_no_urgencia_domicilio_fonasa
      - consulta_no_urgencia_domicilio_no_fonasa
      - consulta_urgencia_domicilio_fonasa
      - consulta_urgencia_domicilio_no_fonasa
      - consulta_odontologica_fonasa
      - consulta_odontologica_no_fonasa
      - consulta_medico_de_referencia_fonasa
      - consulta_medico_de_referencia_no_fonasa
      - endoscopia_digestiva_endoscopia_fonasa
      - endoscopia_digestiva_endoscopia_no_fonasa
      - ecografia_simple_fonasa
      - ecografia_simple_no_fonasa
      - ecodoppler_fonasa
      - ecodoppler_no_fonasa
      - rx_simple_fonasa
      - rx_simple_no_fonasa
      - rx_torax_fonasa
      - rx_torax_no_fonasa
      - rx_colorectal_fonasa
      - rx_colorectal_no_fonasa
      - resonancia_fonasa
      - resonancia_no_fonasa
      - tomografia_fonasa
      - tomografia_no_fonasa
      - laboratorio_rutina_basica_fonasa
      - laboratorio_rutina_basica_no_fonasa
  averages:
    medicamentos:
      columns:
        - ticket_de_medicamentos_general_fonasa
        - ticket_de_medicamentos_general_no_fonasa
        - ticket_de_medicamentos_topeados_fonasa
        - ticket_de_medicamentos_topeados_no_fonasa
    tickets:
      columns:
        - consulta_medicina_general_fonasa
        - consulta_medicina_general_no_fonasa
        - consulta_pediatria_fonasa
        - consulta_pediatria_no_fonasa
        - consulta_control_de_embarazo_fonasa
        - consulta_control_de_embarazo_no_fonasa
        - consulta_ginecologia_fonasa
        - consulta_ginecologia_no_fonasa
        - consulta_otras_especialidades_fonasa
        - consulta_otras_especialidades_no_fonasa
        - consulta_odontologica_fonasa
        - consulta_odontologica_no_fonasa
        - consulta_medico_de_referencia_fonasa
        - consulta_medico_de_referencia_no_fonasa
    tickets_urgentes:
      columns:
        - consulta_urgencia_centralizada_fonasa
        - consulta_urgencia_centralizada_no_fonasa
        - consulta_urgencia_domicilio_fonasa
        - consulta_urgencia_domicilio_no_fonasa
    estudios:
      columns:
        - endoscopia_digestiva_endoscopia_fonasa
        - endoscopia_digestiva_endoscopia_no_fonasa
        - ecografia_simple_fonasa
        - ecografia_simple_no_fonasa
        - ecodoppler_fonasa
        - ecodoppler_no_fonasa
        - rx_simple_fonasa
        - rx_simple_no_fonasa
        - rx_torax_fonasa
        - rx_torax_no_fonasa
        - rx_colorectal_fonasa
        - rx_colorectal_no_fonasa
        - resonancia_fonasa
        - resonancia_no_fonasa
        - tomografia_fonasa
        - tomografia_no_fonasa
        - laboratorio_rutina_basica_fonasa
        - laboratorio_rutina_basica_no_fonasa
sedes:
  description:
    - "Direccion"
    - "Departamento"
    - "Localidad"
    - "Nivel"
    - "Servicio de Urgencia"
    - "Alergista"
    - "Anestesiología"
    - "Cardiología"
    - "Cirugía"
    - "Cirugía Reparadora"
    - "Cirugía Vascular"
    - "Deportología"
    - "Dermatología"
    - "Endocrinolgía"
    - "Fisiatría"
    - "Gastroenterología"
    - "Geriatría"
    - "Ginecología"
    - "Hematología"
    - "Infectología"
    - "Medicina General"
    - "Medicina Interna"
    - "Medicina Intensiva"
    - "Nefrología"
    - "Neonatología"
    - "Neumología"
    - "Neurocirugía"
    - "Neurología"
    - "Neuropediatría"
    - "Odontología"
    - "Oncología"
    - "Otorrinolaringología"
    - "Pediatría"
    - "Psiquiatría"
    - "Psiquiatría Infantil"
    - "Reumatología"
    - "Traumatología"
    - "Urología"
  columns:
    - direccion
    - departamento
    - localidad
    - nivel
    - servicio_de_urgencia
    - alergista
    - anestesiologia
    - cardiologia
    - cirugia
    - cirugia_reparadora
    - cirugia_vascular
    - deportologia
    - dermatologia
    - endocrinolgia
    - fisiatria
    - gastroenterologia
    - geriatria
    - ginecologia
    - hematologia
    - infectologia
    - medicina_general
    - medicina_interna
    - medicina_intensiva
    - nefrologia
    - neonatologia
    - neumologia
    - neurocirugia
    - neurologia
    - neuropediatria
    - odontologia
    - oncologia
    - otorrinolaringologia
    - pediatria
    - psiquiatria
    - psiquiatria_infantil
    - reumatologia
    - traumatologia
    - urologia
  definition:
    string:
      - direccion
      - departamento
      - localidad
      - nivel
    boolean:
      - servicio_de_urgencia
      - alergista
      - anestesiologia
      - cardiologia
      - cirugia
      - cirugia_reparadora
      - cirugia_vascular
      - deportologia
      - dermatologia
      - endocrinolgia
      - fisiatria
      - gastroenterologia
      - geriatria
      - ginecologia
      - hematologia
      - infectologia
      - medicina_general
      - medicina_interna
      - medicina_intensiva
      - nefrologia
      - neonatologia
      - neumologia
      - neurocirugia
      - neurologia
      - neuropediatria
      - odontologia
      - oncologia
      - otorrinolaringologia
      - pediatria
      - psiquiatria
      - psiquiatria_infantil
      - reumatologia
      - traumatologia
      - urologia

tiempos_espera:
  title: "Tiempos de Espera"
  description:
    - "Promedio de tiempo de espera para Medicina General"
    - "Datos suficientes de tiempo de espera para Medicina General"
    - "Promedio de tiempo de espera para Pediatría"
    - "Datos suficientes tiempo de espera para Pediatría"
    - "Promedio de tiempo de espera para Cirugía General"
    - "Datos suficientes de tiempo de espera para Cirugía General"
    - "Promedio de tiempo de espera para Ginecotocología"
    - "Datos suficientes de tiempo de espera para Ginecotocología"
    - "Promedio de tiempo de espera para Médico de Referencia de Medicina General"
    - "Datos suficientes de espera para Médico de Referencia de Medicina General"
  columns:
    - tiempo_espera_medicina_general
    - tiempo_espera_pediatria
    - tiempo_espera_cirugia_general
    - tiempo_espera_ginecotocologia
  definition:
    decimal:
      - tiempo_espera_medicina_general
      - tiempo_espera_pediatria
      - tiempo_espera_cirugia_general
      - tiempo_espera_ginecotocologia

satisfaccion_derechos:
  title: "Satisfacción de derechos"
  description:
    - "Conformidad con disponibilidad de agenda (consulta médica) (2014)"
    - "Conformidad con disponibilidad de agenda (consulta médica) (2010)"
    - "Evaluación de tiempo de espera en sala (2014)"
    - "Evaluación de tiempo de espera en sala (2010)"
    - "Facilidad para realizar trámites y gestiones (2014)"
    - "Facilidad para realizar trámites y gestiones (2010)"
    - "Disponibilidad de medicamentos en farmacia (2014)"
    - "Disponibilidad de medicamentos en farmacia (2010)"
    - "Información sobre Derechos (2014)"
    - "Información sobre Derechos (2010)"
    - "Si hoy tuviese una queja o sugerencia sabe a dónde dirigirse (2014)"
    - "Si hoy tuviese una queja o sugerencia sabe a dónde dirigirse (2010)"
    - "Satisfacción con Primer Nivel de Atención (2014)"
    - "Satisfacción con Primer Nivel de Atención (2010)"
    - "Satisfacción con Internación Hospitalaria (2012)"
  columns:
    - conformidad_disponibilidad_agenda_2014
    - conformidad_disponibilidad_agenda_2010
    - evaluacion_tiempo_espera_sala_2014
    - evaluacion_tiempo_espera_sala_2010
    - facilidad_para_realizar_tramites_gestiones_2014
    - facilidad_para_realizar_tramites_gestiones_2010
    - disponibilidad_medicamentos_farmacia_2014
    - disponibilidad_medicamentos_farmacia_2010
    - informacion_sobre_derechos_2014
    - informacion_sobre_derechos_2010
    - queja_sugerencia_sabe_donde_dirigirse_2014
    - queja_sugerencia_sabe_donde_dirigirse_2010
    - satisfaccion_primer_nivel_atencion_2014
    - satisfaccion_primer_nivel_atencion_2010
    - satisfaccion_internacion_hospitalaria_2012
  definition:
    decimal:
      - conformidad_disponibilidad_agenda_2014
      - conformidad_disponibilidad_agenda_2010
      - evaluacion_tiempo_espera_sala_2014
      - evaluacion_tiempo_espera_sala_2010
      - facilidad_para_realizar_tramites_gestiones_2014
      - facilidad_para_realizar_tramites_gestiones_2010
      - disponibilidad_medicamentos_farmacia_2014
      - disponibilidad_medicamentos_farmacia_2010
      - informacion_sobre_derechos_2014
      - informacion_sobre_derechos_2010
      - queja_sugerencia_sabe_donde_dirigirse_2014
      - queja_sugerencia_sabe_donde_dirigirse_2010
      - satisfaccion_primer_nivel_atencion_2014
      - satisfaccion_primer_nivel_atencion_2010
      - satisfaccion_internacion_hospitalaria_2012


rrhh:
  title: "Recursos Humanos"
  description:
    - "Cargos de médicos generales en policlínica cada 10.000 usuarios mayores de 14 años"
    - "Cargos de médicos de familia en policlínica cada 10.000 usuarios"
    - "Cargos de médicos pediatras en policlínica cada 10.000 usuarios menores de 14 años"
    - "Cargos de médicos ginecólogos en policlínica cada 10.000 usuarios mayores de 14 años"
    - "Cargos de auxiliares de enfermería en policlínica cada 10.000 usuarios"
    - "Cargos de licenciadas de enfermería en policlínica cada 10.000 usuarios"
    - "Cantidad de CAD cada 10.000 usuarios "
    - "Medicina General Cantidad de CAD"
    - "Medicina Familiar Cantidad de CAD"
    - "Pediatría Cantidad de CAD"
    - "Ginecotología Cantidad de CAD"
    - "Medicina Interna Cantidad de CAD"
    - "Medicina Intensiva de Adultos Cantidad de CAD"
    - "Medicina Intensiva Pediátrica Cantidad de CAD"
    - "Neonatología Cantidad de CAD"
  columns:
    - medicos_generales_policlinica
    - medicos_de_familia_policlinica
    - medicos_pediatras_policlinica
    - medicos_ginecologos_policlinica
    - auxiliares_enfermeria_policlinica
    - licenciadas_enfermeria_policlinica
    - cantidad_cad
    - medicina_general_cantidad_cad
    - medicina_familiar_cantidad_cad
    - pediatria_cantidad_cad
    - ginecotologia_cantidad_cad
    - medicina_interna_cantidad_cad
    - medicina_intensiva_adultos_cantidad_cad
    - medicina_intensiva_pediatrica_cantidad_cad
    - neonatologia_cantidad_cad
  definition:
    decimal:
      - medicos_generales_policlinica
      - medicos_de_familia_policlinica
      - medicos_pediatras_policlinica
      - medicos_ginecologos_policlinica
      - auxiliares_enfermeria_policlinica
      - licenciadas_enfermeria_policlinica
      - cantidad_cad
      - medicina_general_cantidad_cad
      - medicina_familiar_cantidad_cad
      - pediatria_cantidad_cad
      - ginecotologia_cantidad_cad
      - medicina_interna_cantidad_cad
      - medicina_intensiva_adultos_cantidad_cad
      - medicina_intensiva_pediatrica_cantidad_cad
      - neonatologia_cantidad_cad


solicitud_consultas:
  title: "Solicitud de consultas"
  description:
    - "Vias de asignación de citas"
    - "Realiza recordatorio de cita"
    - "Realiza caída de reserva en determinado tiempo antes/después del inicio de la consulta si no es confirmada"
    - "Comunicación con el usuario por suspensión o modificación de la consulta"
  columns:
    - vias_asignacion_citas
    - realiza_recordatorio_cita
    - realiza_caida_reserva_sin_confirmacion
    - comunicacion_usuario_suspension_modificacion
  definition:
    string:
      - reserva_presencial
      - reserva_telefonica
      - reserva_web
      - reserva_consulta_medica
      - realiza_recordatorio_cita
      - realiza_caida_reserva_sin_confirmacion
      - comunicacion_usuario_suspension_modificacion
#
# ll:
#   description:
#   columns:
#   definition:
#     string:
#     integer:
